// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shvnmdhamqajanusqfax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNodm5tZGhhbXFhamFudXNxZmF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzNjIyMzEsImV4cCI6MjA1MDkzODIzMX0.mR67BRDB56RfIko84wZc2g5kUOZ7zg4sfgD237C51uU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);